name: Lint php documentation

on:
  #push:
  workflow_dispatch:   # manual trigger
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

permissions:
  contents: read

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint phpdoc blocks
        uses: sudo-bot/action-doctum@v5
        with:
          config-file: tests/doctum-config.php
          method: "parse"
          cli-args: "--output-format=github --no-ansi --no-progress -v --ignore-parse-errors"
