name: "Manage stale PRs/issues"

permissions:
  issues: write

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  run-stale-check:
    name: Check for stale PRs/issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 15
          days-before-close: -1
          only-issue-labels: "Awaiting Author Updates"
          close-issue-message: >
            The phpMyAdmin team is awaiting an update on this issue.
            Please check that all the questions have been answered.
