name: Run Specific PHPUnit Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  run-specific-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Adjust to your project's PHP version (e.g., '7.4', '8.0', '8.2', '8.3')
        extensions: gd # Required for the GD extension test, add other necessary extensions like 'mysqli', 'pdo_mysql', etc.
        coverage: none # Or 'xdebug', 'pcov' if you need code coverage

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Create test directory for expected files (if it doesn't exist)
      run: mkdir -p tests/test_data/gis

    - name: Run specific GisLineStringTest::testPrepareRowAsPdf test
      run: vendor/bin/phpunit --no-coverage tests/unit/Gis/GisLineStringTest.php --filter testPrepareRowAsPdf

    - name: Run specific GisMultiPolygonTest::testPrepareRowAsPdf test
      run: vendor/bin/phpunit --no-coverage tests/unit/Gis/GisMultiPolygonTest.php --filter testPrepareRowAsPdf
      working-directory: ./ # If your project root is where vendor/bin is, otherwise adjust

    # Upload the generated actual PDF files regardless of test success or failure
    - name: Upload generated LineString PDF artifact
      # Change 'if: failure()' to 'if: always()' or remove the 'if' condition entirely
      # 'if: always()' ensures it runs even if previous steps fail
      # Removing the 'if' condition (default behavior) means it only runs if previous steps succeed
      # Given you want to see it even on success, 'if: always()' is robust.
      uses: actions/upload-artifact@v4
      with:
        name: linestring-actual-pdf
        path: tests/test_data/gis/linestring-actual.pdf # Adjust this path
        retention-days: 5

    - name: Upload generated MultiPolygon PDF artifact
      # Same as above, choose 'if: always()' or no 'if' condition
      uses: actions/upload-artifact@v4
      with:
        name: multipolygon-actual-pdf
        path: tests/test_data/gis/multipolygon-actual.pdf # Adjust this path
        retention-days: 5
